--
-- High-Performance Single-Statement Batch Update for Turso / libSQL
-- Executes in a single query roundtrip
--
UPDATE Schemes
SET Difficulty = CASE
  WHEN Id = 'scheme-control-the-mutant-messiah' OR Name = '...Control the Mutant Messiah' THEN 'Moderate'
  WHEN Id = 'scheme-open-rifts-to-future-timelines' OR Name = '...Open Rifts to Future Timelines' THEN 'Hard'
  WHEN Id = 'scheme-reveal-the-heroes-evil-clones' OR Name = '...Reveal The Heroes'' Evil Clones' THEN 'Moderate'
  WHEN Id = 'scheme-unleash-an-anti-mutant-bioweapon' OR Name = '...Unleash an Anti-Mutant Bioweapon' THEN 'Extreme'
  WHEN Id = 'scheme-age-of-ultron' OR Name = 'Age of Ultron' THEN 'Easy'
  WHEN Id = 'scheme-alien-brood-encounters' OR Name = 'Alien Brood Encounters' THEN 'Hard'
  WHEN Id = 'scheme-annihilation-conquest' OR Name = 'Annihilation: Conquest' THEN 'Hard'
  WHEN Id = 'scheme-anti-mutant-hatred' OR Name = 'Anti-Mutant Hatred' THEN 'Extreme'
  WHEN Id = 'scheme-asgard-under-siege' OR Name = 'Asgard Under Siege' THEN 'Hard'
  WHEN Id = 'scheme-asgardian-test-of-worth' OR Name = 'Asgardian Test of Worth' THEN 'Easy'
  WHEN Id = 'scheme-auction-shrink-tech-to-highest-bidder' OR Name = 'Auction Shrink Tech to Highest Bidder' THEN 'Easy'
  WHEN Id = 'scheme-avengers-vs-x-men' OR Name = 'Avengers vs. X-Men' THEN 'Hard'
  WHEN Id = 'scheme-bank-robbery-hostage-crisis' OR Name = 'Bank Robbery Hostage Crisis' THEN 'Hard'
  WHEN Id = 'scheme-bathe-the-earth-in-cosmic-rays' OR Name = 'Bathe the Earth in Cosmic Rays' THEN 'Extreme'
  WHEN Id = 'scheme-become-president-of-the-united-states' OR Name = 'Become President of the United States' THEN 'Easy'
  WHEN Id = 'scheme-befoul-earth-into-a-polluted-wasteland' OR Name = 'Befoul Earth Into a Polluted Wasteland' THEN 'Hard'
  WHEN Id = 'scheme-brainwash-the-military' OR Name = 'Brainwash the Military' THEN 'Hard'
  WHEN Id = 'scheme-breach-parallel-dimensions' OR Name = 'Breach Parallel Dimensions' THEN 'Hard'
  WHEN Id = 'scheme-breach-the-nexus-of-all-realities' OR Name = 'Breach the Nexus of All Realities' THEN 'Hard'
  WHEN Id = 'scheme-break-open-star-labs-virus-bank' OR Name = 'Break Open S.T.A.R. Labs Virus Bank' THEN 'Moderate'
  WHEN Id = 'scheme-break-the-planet-asunder' OR Name = 'Break the Planet Asunder' THEN 'Moderate'
  WHEN Id = 'scheme-build-an-army-of-annihilation' OR Name = 'Build an Army of Annihilation' THEN 'Moderate'
  WHEN Id = 'scheme-build-an-underground-megavault-prison' OR Name = 'Build an Underground MegaVault Prison' THEN 'Moderate'
  WHEN Id = 'scheme-cage-villains-in-power-suppressing-cells' OR Name = 'Cage Villains in Power-Suppressing Cells' THEN 'Moderate'
  WHEN Id = 'scheme-capture-baby-hope' OR Name = 'Capture Baby Hope' THEN 'Moderate'
  WHEN Id = 'scheme-change-the-outcome-of-wwii' OR Name = 'Change the Outcome of WWII' THEN 'Hard'
  WHEN Id = 'scheme-claim-souls-for-demons' OR Name = 'Claim Souls for Demons' THEN 'Moderate'
  WHEN Id = 'scheme-clash-of-the-monsters-unleashed' OR Name = 'Clash of the Monsters Unleashed' THEN 'Hard'
  WHEN Id = 'scheme-collect-an-interstellar-zoo' OR Name = 'Collect an Interstellar Zoo' THEN 'Moderate'
  WHEN Id = 'scheme-condition-logan-into-weapon-x' OR Name = 'Condition Logan into Weapon X' THEN 'Moderate'
  WHEN Id = 'scheme-conquer-paradise-island' OR Name = 'Conquer Paradise Island of Themyscira' THEN 'Moderate'
  WHEN Id = 'scheme-corrupt-leaders-gotham-city' OR Name = 'Corrupt the Leaders of Gotham City' THEN 'Moderate'
  WHEN Id = 'scheme-corrupt-the-next-generation-of-heroes' OR Name = 'Corrupt the Next Generation of Heroes' THEN 'Extreme'
  WHEN Id = 'scheme-corrupt-the-spy-agencies' OR Name = 'Corrupt the Spy Agencies' THEN 'Moderate'
  WHEN Id = 'scheme-crash-the-moon-into-the-sun' OR Name = 'Crash the Moon into the Sun' THEN 'Easy'
  WHEN Id = 'scheme-crown-thor-king-of-asgard' OR Name = 'Crown Thor King of Asgard' THEN 'Moderate'
  WHEN Id = 'scheme-crush-hydra' OR Name = 'Crush HYDRA' THEN 'Moderate'
  WHEN Id = 'scheme-crush-them-with-my-bare-hands' OR Name = 'Crush Them With My Bare Hands' THEN 'Extreme'
  WHEN Id = 'scheme-cursed-pages-of-the-darkhold-tome' OR Name = 'Cursed Pages of the Darkhold Tome' THEN 'Moderate'
  WHEN Id = 'scheme-cytoplasm-spike-invasion' OR Name = 'Cytoplasm Spike Invasion' THEN 'Easy'
  WHEN Id = 'scheme-dark-alliance' OR Name = 'Dark Alliance' THEN 'Extreme'
  WHEN Id = 'scheme-dark-reign-of-hammer-officers' OR Name = 'Dark Reign of H.A.M.M.E.R. Officers' THEN 'Moderate'
  WHEN Id = 'scheme-deadlands-hordes-charge-the-wall' OR Name = 'Deadlands Hordes Charge the Wall' THEN 'Hard'
  WHEN Id = 'scheme-deadpool-kills-the-marvel-universe' OR Name = 'Deadpool Kills the Marvel Universe' THEN 'Hard'
  WHEN Id = 'scheme-deadpool-wants-a-chimichanga' OR Name = 'Deadpool Wants a Chimichanga' THEN 'Hard'
  WHEN Id = 'scheme-deadpool-writes-a-scheme' OR Name = 'Deadpool Writes a Scheme' THEN 'Extreme'
  WHEN Id = 'scheme-demonic-incursion-earth' OR Name = 'Demonic Incursion of the Earth Realm' THEN 'Moderate'
  WHEN Id = 'scheme-destroy-the-cities-of-earth' OR Name = 'Destroy the Cities of Earth!' THEN 'Moderate'
  WHEN Id = 'scheme-destroy-the-nova-corps' OR Name = 'Destroy the Nova Corps' THEN 'Moderate'
  WHEN Id = 'scheme-detonate-the-helicarrier' OR Name = 'Detonate the Helicarrier' THEN 'Moderate'
  WHEN Id = 'scheme-devolve-with-xerogen-crystals' OR Name = 'Devolve with Xerogen Crystals' THEN 'Moderate'
  WHEN Id = 'scheme-distract-the-hero' OR Name = 'Distract the Hero' THEN 'Moderate'
  WHEN Id = 'scheme-divide-and-conquer' OR Name = 'Divide and Conquer' THEN 'Hard'
  WHEN Id = 'scheme-drain-mutant-powers-to' OR Name = 'Drain Mutant Powers To...' THEN 'Easy'
  WHEN Id = 'scheme-duels-of-science-and-magic' OR Name = 'Duels of Science and Magic' THEN 'Moderate'
  WHEN Id = 'scheme-earthquake-drains-the-ocean' OR Name = 'Earthquake Drains the Ocean' THEN 'Hard'
  WHEN Id = 'scheme-eclipse-light-of-magic' OR Name = 'Eclipse the Light of Magic' THEN 'Moderate'
  WHEN Id = 'scheme-enshrouded-identity' OR Name = 'Enshrouded Identity' THEN 'Extreme'
  WHEN Id = 'scheme-enslave-minds-with-the-chitauri-scepter' OR Name = 'Enslave Minds with the Chitauri Scepter' THEN 'Moderate'
  WHEN Id = 'scheme-enthrone-the-barons-of-battleworld' OR Name = 'Enthrone the Barons of Battleworld' THEN 'Hard'
  WHEN Id = 'scheme-epic-super-hero-civil-war' OR Name = 'Epic Super Hero Civil War' THEN 'Easy'
  WHEN Id = 'scheme-escape-an-imprisoning-dimension' OR Name = 'Escape an Imprisoning Dimension' THEN 'Hard'
  WHEN Id = 'scheme-everybody-hates-deadpool' OR Name = 'Everybody Hates Deadpool' THEN 'Extreme'
  WHEN Id = 'scheme-explosion-at-the-washington-monument' OR Name = 'Explosion at the Washington Monument' THEN 'Moderate'
  WHEN Id = 'scheme-fall-of-the-hulks' OR Name = 'Fall of the Hulks' THEN 'Easy'
  WHEN Id = 'scheme-fear-itself' OR Name = 'Fear Itself' THEN 'Hard'
  WHEN Id = 'scheme-ferry-disaster' OR Name = 'Ferry Disaster' THEN 'Moderate'
  WHEN Id = 'scheme-find-the-split-personality-killer' OR Name = 'Find the Split Personality Killer' THEN 'Moderate'
  WHEN Id = 'scheme-five-families-of-crime' OR Name = 'Five Families of Crime' THEN 'Hard'
  WHEN Id = 'scheme-flood-the-planet-with-melted-glaciers' OR Name = 'Flood the Planet with Melted Glaciers' THEN 'Moderate'
  WHEN Id = 'scheme-forge-the-infinity-gauntlet' OR Name = 'Forge the Infinity Gauntlet' THEN 'Moderate'
  WHEN Id = 'scheme-fragmented-realities' OR Name = 'Fragmented Realities' THEN 'Extreme'
  WHEN Id = 'scheme-frame-heroes-for-murder' OR Name = 'Frame Heroes for Murder' THEN 'Moderate'
  WHEN Id = 'scheme-gladiator-pits-of-sakaar' OR Name = 'Gladiator Pits of Sakaar' THEN 'Extreme'
  WHEN Id = 'scheme-go-after-heroes-loved-ones' OR Name = 'Go After Heroes'' Loved Ones' THEN 'Moderate'
  WHEN Id = 'scheme-go-back-in-time-to-slay-heroes-ancestors' OR Name = 'Go Back in Time to Slay Heroes'' Ancestors' THEN 'Moderate'
  WHEN Id = 'scheme-graduation-at-xaviers-x-academy' OR Name = 'Graduation at Xavier''s X-Academy' THEN 'Moderate'
  WHEN Id = 'scheme-hack-cerebro-servers-to' OR Name = 'Hack Cerebro Servers To...' THEN 'Easy'
  WHEN Id = 'scheme-hail-hydra' OR Name = 'Hail Hydra' THEN 'Easy'
  WHEN Id = 'scheme-halve-all-life-in-the-universe' OR Name = 'Halve All Life in the Universe' THEN 'Hard'
  WHEN Id = 'scheme-hidden-heart-of-darkness' OR Name = 'Hidden Heart of Darkness' THEN 'Moderate'
  WHEN Id = 'scheme-hire-singularity-investigations-to' OR Name = 'Hire Singularity Investigations To...' THEN 'Moderate'
  WHEN Id = 'scheme-horror-of-horrors' OR Name = 'Horror of Horrors' THEN 'Extreme'
  WHEN Id = 'scheme-house-of-m' OR Name = 'House of M' THEN 'Moderate'
  WHEN Id = 'scheme-hydra-helicarriers-hunt-heroes' OR Name = 'Hydra Helicarriers Hunt Heroes' THEN 'Moderate'
  WHEN Id = 'scheme-hypnotize-every-human' OR Name = 'Hypnotize Every Human' THEN 'Moderate'
  WHEN Id = 'scheme-imprison-unregistered-superhumans' OR Name = 'Imprison Unregistered Superhumans' THEN 'Hard'
  WHEN Id = 'scheme-inescapable-kyln-space-prison' OR Name = 'Inescapable “Kyln“ Space Prison' THEN 'Hard'
  WHEN Id = 'scheme-infiltrate-the-lair-with-spies' OR Name = 'Infiltrate the Lair with Spies' THEN 'Moderate'
  WHEN Id = 'scheme-intergalactic-kree-nega-bomb' OR Name = 'Intergalactic Kree Nega-Bomb' THEN 'Moderate'
  WHEN Id = 'scheme-invade-asgard' OR Name = 'Invade Asgard' THEN 'Moderate'
  WHEN Id = 'scheme-invade-the-daily-bugle-news-hq' OR Name = 'Invade the Daily Bugle News HQ' THEN 'Hard'
  WHEN Id = 'scheme-invasion-of-the-venom-symbiotes' OR Name = 'Invasion of the Venom Symbiotes' THEN 'Moderate'
  WHEN Id = 'scheme-invincible-force-field' OR Name = 'Invincible Force Field' THEN 'Moderate'
  WHEN Id = 'scheme-kingdom-come' OR Name = 'Kingdom Come' THEN 'Moderate'
  WHEN Id = 'scheme-lash-city-deadly-tornado' OR Name = 'Lash City with Deadly Tornado' THEN 'Moderate'
  WHEN Id = 'scheme-last-stand-at-avengers-tower' OR Name = 'Last Stand at Avengers Tower' THEN 'Hard'
  WHEN Id = 'scheme-marvel-zombies' OR Name = 'Marvel Zombies' THEN 'Extreme'
  WHEN Id = 'scheme-mass-produce-war-machine-armor' OR Name = 'Mass Produce War Machine Armor' THEN 'Moderate'
  WHEN Id = 'scheme-massive-earthquake-generator' OR Name = 'Massive Earthquake Generator' THEN 'Extreme'
  WHEN Id = 'scheme-master-of-tyrants' OR Name = 'Master of Tyrants' THEN 'Moderate'
  WHEN Id = 'scheme-master-the-mysteries-of-kung-fu' OR Name = 'Master the Mysteries of Kung-Fu' THEN 'Moderate'
  WHEN Id = 'scheme-maximum-carnage' OR Name = 'Maximum Carnage' THEN 'Hard'
  WHEN Id = 'scheme-merge-earth-bizarro-world' OR Name = 'Merge Earth with Bizarro World' THEN 'Moderate'
  WHEN Id = 'scheme-midnight-massacre' OR Name = 'Midnight Massacre' THEN 'Easy'
  WHEN Id = 'scheme-midtown-bank-robbery' OR Name = 'Midtown Bank Robbery' THEN 'Easy'
  WHEN Id = 'scheme-mutant-hunting-super-sentinels' OR Name = 'Mutant-Hunting Super Sentinels' THEN 'Moderate'
  WHEN Id = 'scheme-mutating-gamma-rays' OR Name = 'Mutating Gamma Rays' THEN 'Hard'
  WHEN Id = 'scheme-negative-zone-prison-breakout' OR Name = 'Negative Zone Prison Breakout' THEN 'Extreme'
  WHEN Id = 'scheme-negative-zone-prison-breakout-base' OR Name = 'Negative Zone Prison Breakout' THEN 'Moderate'
  WHEN Id = 'scheme-nitro-the-supervillain-threatens-crowds' OR Name = 'Nitro the Supervillain Threatens Crowds' THEN 'Moderate'
  WHEN Id = 'scheme-nuclear-armageddon' OR Name = 'Nuclear Armageddon' THEN 'Hard'
  WHEN Id = 'scheme-organized-crime-wave' OR Name = 'Organized Crime Wave' THEN 'Moderate'
  WHEN Id = 'scheme-pan-dimensional-plague' OR Name = 'Pan-Dimensional Plague' THEN 'Easy'
  WHEN Id = 'scheme-paralyzing-venom' OR Name = 'Paralyzing Venom' THEN 'Extreme'
  WHEN Id = 'scheme-plunder-wakandas-vibranium' OR Name = 'Plunder Wakanda''s Vibranium' THEN 'Easy'
  WHEN Id = 'scheme-poison-lakes-with-nanite-microbots' OR Name = 'Poison Lakes with Nanite Microbots' THEN 'Moderate'
  WHEN Id = 'scheme-portals-to-the-dark-dimension' OR Name = 'Portals to the Dark Dimension' THEN 'Moderate'
  WHEN Id = 'scheme-portals-to-the-dark-dimension-base' OR Name = 'Portals to the Dark Dimension' THEN 'Moderate'
  WHEN Id = 'scheme-predict-future-crime' OR Name = 'Predict Future Crime' THEN 'Extreme'
  WHEN Id = 'scheme-provoke-a-clash-of-nations' OR Name = 'Provoke a Clash of Nations' THEN 'Moderate'
  WHEN Id = 'scheme-provoke-the-sovereign-war-fleet' OR Name = 'Provoke the Sovereign War Fleet' THEN 'Moderate'
  WHEN Id = 'scheme-pull-earth-into-medieval-times' OR Name = 'Pull Earth into Medieval Times' THEN 'Hard'
  WHEN Id = 'scheme-pull-reality-into-cyberspace' OR Name = 'Pull Reality Into Cyberspace' THEN 'Moderate'
  WHEN Id = 'scheme-pull-reality-into-the-negative-zone' OR Name = 'Pull Reality Into the Negative Zone' THEN 'Extreme'
  WHEN Id = 'scheme-pulse-waves-from-the-negative-zone' OR Name = 'Pulse Waves From the Negative Zone' THEN 'Moderate'
  WHEN Id = 'scheme-put-humanity-on-trial' OR Name = 'Put Humanity on Trial' THEN 'Easy'
  WHEN Id = 'scheme-radioactive-palladium-poisoning' OR Name = 'Radioactive Palladium Poisoning' THEN 'Moderate'
  WHEN Id = 'scheme-ragnarok-twilight-of-the-gods' OR Name = 'Ragnarok, Twilight of the Gods' THEN 'Easy'
  WHEN Id = 'scheme-raid-gene-banks-to' OR Name = 'Raid Gene Banks To...' THEN 'Moderate'
  WHEN Id = 'scheme-replace-earths-leaders-with-hydra' OR Name = 'Replace Earth''s Leaders with HYDRA' THEN 'Hard'
  WHEN Id = 'scheme-replace-earths-leaders-with-killbots' OR Name = 'Replace Earth''s Leaders with Killbots' THEN 'Easy'
  WHEN Id = 'scheme-replace-earths-leaders-with-killbots-base' OR Name = 'Replace Earth''s Leaders with Killbots' THEN 'Hard'
  WHEN Id = 'scheme-resurrect-heroes-with-norn-stones' OR Name = 'Resurrect Heroes with Norn Stones' THEN 'Moderate'
  WHEN Id = 'scheme-reveal-heroes-secret-identities' OR Name = 'Reveal Heroes'' Secret Identities' THEN 'Extreme'
  WHEN Id = 'scheme-ritual-sacrifice-to-summon-chthon' OR Name = 'Ritual Sacrifice to Summon Chthon' THEN 'Extreme'
  WHEN Id = 'scheme-ruin-the-perfect-wedding' OR Name = 'Ruin the Perfect Wedding' THEN 'Easy'
  WHEN Id = 'scheme-shield-vs-hydra-war' OR Name = 'S.H.I.E.L.D. vs. HYDRA War' THEN 'Moderate'
  WHEN Id = 'scheme-sacrifice-for-the-soul-stone' OR Name = 'Sacrifice for the Soul Stone' THEN 'Moderate'
  WHEN Id = 'scheme-safeguard-dark-secrets' OR Name = 'Safeguard Dark Secrets' THEN 'Hard'
  WHEN Id = 'scheme-save-humanity' OR Name = 'Save Humanity' THEN 'Easy'
  WHEN Id = 'scheme-scavenge-alien-weaponry' OR Name = 'Scavenge Alien Weaponry' THEN 'Extreme'
  WHEN Id = 'scheme-secret-empire-of-betrayal' OR Name = 'Secret Empire of Betrayal' THEN 'Hard'
  WHEN Id = 'scheme-secret-hydra-corruption' OR Name = 'Secret HYDRA Corruption' THEN 'Moderate'
  WHEN Id = 'scheme-secret-invasion-of-the-skrull-shapeshifters' OR Name = 'Secret Invasion of the Skrull Shapeshifters' THEN 'Hard'
  WHEN Id = 'scheme-secret-invasion-of-the-skrull-shapeshifters-base' OR Name = 'Secret Invasion of the Skrull Shapeshifters' THEN 'Moderate'
  WHEN Id = 'scheme-secret-wars' OR Name = 'Secret Wars' THEN 'Hard'
  WHEN Id = 'scheme-seize-the-wakandan-throne' OR Name = 'Seize the Wakandan Throne' THEN 'Hard'
  WHEN Id = 'scheme-shoot-hulk-into-space' OR Name = 'Shoot Hulk into Space' THEN 'Moderate'
  WHEN Id = 'scheme-silence-the-witnesses' OR Name = 'Silence the Witnesses' THEN 'Hard'
  WHEN Id = 'scheme-sinister-ambitions' OR Name = 'Sinister Ambitions' THEN 'Extreme'
  WHEN Id = 'scheme-siphon-energy-from-the-quantum-realm' OR Name = 'Siphon Energy from the Quantum Realm' THEN 'Moderate'
  WHEN Id = 'scheme-sire-vampires-at-the-blood-bank' OR Name = 'Sire Vampires at the Blood Bank' THEN 'Easy'
  WHEN Id = 'scheme-smash-two-dimensions-together' OR Name = 'Smash Two Dimensions Together' THEN 'Extreme'
  WHEN Id = 'scheme-sneak-attack-the-heroes-homes' OR Name = 'Sneak Attack the Heroes'' Homes' THEN 'Hard'
  WHEN Id = 'scheme-sniper-rifle-assassins' OR Name = 'Sniper Rifle Assassins' THEN 'Easy'
  WHEN Id = 'scheme-splice-humans-with-spider-dna' OR Name = 'Splice Humans with Spider DNA' THEN 'Moderate'
  WHEN Id = 'scheme-star-lords-awesome-mix-tape' OR Name = 'Star-Lord''s Awesome Mix Tape' THEN 'Moderate'
  WHEN Id = 'scheme-steal-all-oxygen-on-earth' OR Name = 'Steal All Oxygen on Earth' THEN 'Moderate'
  WHEN Id = 'scheme-steal-the-weaponized-plutonium' OR Name = 'Steal the Weaponized Plutonium' THEN 'Easy'
  WHEN Id = 'scheme-subjugate-earth-with-mega-corporations' OR Name = 'Subjugate Earth with Mega-Corporations' THEN 'Easy'
  WHEN Id = 'scheme-subjugate-with-obedience-disks' OR Name = 'Subjugate with Obedience Disks' THEN 'Easy'
  WHEN Id = 'scheme-super-hero-civil-war' OR Name = 'Super Hero Civil War' THEN 'Easy'
  WHEN Id = 'scheme-superhero-civil-war' OR Name = 'Superhero Civil War' THEN 'Hard'
  WHEN Id = 'scheme-superhuman-baseball-game' OR Name = 'Superhuman Baseball Game' THEN 'Hard'
  WHEN Id = 'scheme-symbiotic-absorption' OR Name = 'Symbiotic Absorption' THEN 'Hard'
  WHEN Id = 'scheme-televised-deathtraps-of-mojoworld' OR Name = 'Televised Deathtraps of Mojoworld' THEN 'Easy'
  WHEN Id = 'scheme-terrorize-citizens-joker-venom' OR Name = 'Terrorize Citizens with Joker Venom' THEN 'Moderate'
  WHEN Id = 'scheme-12-labors-all-star-superman' OR Name = 'The 12 Labors of All-Star Superman' THEN 'Moderate'
  WHEN Id = 'scheme-clone-saga-the' OR Name = 'The Clone Saga' THEN 'Hard'
  WHEN Id = 'scheme-contest-of-champions-the' OR Name = 'The Contest of Champions' THEN 'Easy'
  WHEN Id = 'scheme-dark-phoenix-saga-the' OR Name = 'The Dark Phoenix Saga' THEN 'Moderate'
  WHEN Id = 'scheme-dark-world-of-svartalfheim-the' OR Name = 'The Dark World of Svartalfheim' THEN 'Extreme'
  WHEN Id = 'scheme-demon-bear-saga-the' OR Name = 'The Demon Bear Saga' THEN 'Hard'
  WHEN Id = 'scheme-fountain-of-eternal-life-the' OR Name = 'The Fountain of Eternal Life' THEN 'Moderate'
  WHEN Id = 'scheme-god-emperor-of-battleworld-the' OR Name = 'The God-Emperor of Battleworld' THEN 'Hard'
  WHEN Id = 'scheme-korvac-saga-the' OR Name = 'The Korvac Saga' THEN 'Moderate'
  WHEN Id = 'scheme-kree-skrull-war-the' OR Name = 'The Kree-Skrull War' THEN 'Hard'
  WHEN Id = 'scheme-legacy-virus-the' OR Name = 'The Legacy Virus' THEN 'Easy'
  WHEN Id = 'scheme-legacy-virus-the-base' OR Name = 'The Legacy Virus' THEN 'Easy'
  WHEN Id = 'scheme-mark-of-khonshu-the' OR Name = 'The Mark of Khonshu' THEN 'Easy'
  WHEN Id = 'scheme-the-time-heist' OR Name = 'The Time Heist' THEN 'Easy'
  WHEN Id = 'scheme-traitor-the' OR Name = 'The Traitor' THEN 'Moderate'
  WHEN Id = 'scheme-unbreakable-enigma-code-the' OR Name = 'The Unbreakable Enigma Code' THEN 'Hard'
  WHEN Id = 'scheme-tornado-of-terrigen-mists' OR Name = 'Tornado of Terrigen Mists' THEN 'Easy'
  WHEN Id = 'scheme-train-black-widows-in-the-red-room' OR Name = 'Train Black Widows in the Red Room' THEN 'Moderate'
  WHEN Id = 'scheme-transform-citizens-into-demons' OR Name = 'Transform Citizens Into Demons' THEN 'Extreme'
  WHEN Id = 'scheme-transform-commuters-into-giant-ants' OR Name = 'Transform Commuters into Giant Ants' THEN 'Moderate'
  WHEN Id = 'scheme-trap-heroes-in-the-microverse' OR Name = 'Trap Heroes in the Microverse' THEN 'Hard'
  WHEN Id = 'scheme-trapped-in-the-insane-asylum' OR Name = 'Trapped in the Insane Asylum' THEN 'Extreme'
  WHEN Id = 'scheme-trash-earth-with-hugest-party-ever' OR Name = 'Trash Earth with Hugest Party Ever' THEN 'Hard'
  WHEN Id = 'scheme-turn-the-soul-of-adam-warlock' OR Name = 'Turn the Soul of Adam Warlock' THEN 'Easy'
  WHEN Id = 'scheme-unite-the-shards' OR Name = 'Unite the Shards' THEN 'Moderate'
  WHEN Id = 'scheme-united-states-split-by-civil-war' OR Name = 'United States Split by Civil War' THEN 'Easy'
  WHEN Id = 'scheme-unleash-the-abilisk-space-monster' OR Name = 'Unleash the Abilisk Space Monster' THEN 'Moderate'
  WHEN Id = 'scheme-unleash-the-power-of-the-cosmic-cube' OR Name = 'Unleash the Power of the Cosmic Cube' THEN 'Easy'
  WHEN Id = 'scheme-unleash-the-power-of-the-cosmic-cube-base' OR Name = 'Unleash the Power of the Cosmic Cube' THEN 'Easy'
  WHEN Id = 'scheme-wager-at-blackjack-for-heroes-souls' OR Name = 'Wager at Blackjack for Heroes'' Souls' THEN 'Easy'
  WHEN Id = 'scheme-war-for-the-dream-dimension' OR Name = 'War for the Dream Dimension' THEN 'Hard'
  WHEN Id = 'scheme-war-of-kings' OR Name = 'War of Kings' THEN 'Easy'
  WHEN Id = 'scheme-war-of-the-frost-giants' OR Name = 'War of the Frost Giants' THEN 'Moderate'
  WHEN Id = 'scheme-warp-reality-into-a-tv-show' OR Name = 'Warp Reality into a TV Show' THEN 'Easy'
  WHEN Id = 'scheme-weaponize-chemo-against-city' OR Name = 'Weaponize Chemo Against the City' THEN 'Moderate'
  WHEN Id = 'scheme-weave-a-web-of-lies' OR Name = 'Weave a Web of Lies' THEN 'Moderate'
  WHEN Id = 'scheme-wipe-heroes-memories' OR Name = 'Wipe Heroes'' Memories' THEN 'Moderate'
  WHEN Id = 'scheme-world-war-hulk' OR Name = 'World War Hulk' THEN 'Extreme'
  WHEN Id = 'scheme-x-cutioners-song' OR Name = 'X-Cutioner''s Song' THEN 'Extreme'
  WHEN Id = 'scheme-x-men-danger-room-goes-berserk' OR Name = 'X-Men Danger Room Goes Berserk' THEN 'Moderate'
  ELSE Difficulty
END;