--
-- Turso / SQLite Migration Script for Legendary Scheme Difficulties
-- Compatible with: Turso CLI, SQLite3 CLI, DBeaver, TablePlus, libSQL
--
BEGIN TRANSACTION;

UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-control-the-mutant-messiah' OR Name = '...Control the Mutant Messiah';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-open-rifts-to-future-timelines' OR Name = '...Open Rifts to Future Timelines';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-reveal-the-heroes-evil-clones' OR Name = '...Reveal The Heroes'' Evil Clones';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-unleash-an-anti-mutant-bioweapon' OR Name = '...Unleash an Anti-Mutant Bioweapon';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-age-of-ultron' OR Name = 'Age of Ultron';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-alien-brood-encounters' OR Name = 'Alien Brood Encounters';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-annihilation-conquest' OR Name = 'Annihilation: Conquest';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-anti-mutant-hatred' OR Name = 'Anti-Mutant Hatred';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-asgard-under-siege' OR Name = 'Asgard Under Siege';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-asgardian-test-of-worth' OR Name = 'Asgardian Test of Worth';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-auction-shrink-tech-to-highest-bidder' OR Name = 'Auction Shrink Tech to Highest Bidder';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-avengers-vs-x-men' OR Name = 'Avengers vs. X-Men';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-bank-robbery-hostage-crisis' OR Name = 'Bank Robbery Hostage Crisis';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-bathe-the-earth-in-cosmic-rays' OR Name = 'Bathe the Earth in Cosmic Rays';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-become-president-of-the-united-states' OR Name = 'Become President of the United States';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-befoul-earth-into-a-polluted-wasteland' OR Name = 'Befoul Earth Into a Polluted Wasteland';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-brainwash-the-military' OR Name = 'Brainwash the Military';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-breach-parallel-dimensions' OR Name = 'Breach Parallel Dimensions';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-breach-the-nexus-of-all-realities' OR Name = 'Breach the Nexus of All Realities';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-break-open-star-labs-virus-bank' OR Name = 'Break Open S.T.A.R. Labs Virus Bank';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-break-the-planet-asunder' OR Name = 'Break the Planet Asunder';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-build-an-army-of-annihilation' OR Name = 'Build an Army of Annihilation';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-build-an-underground-megavault-prison' OR Name = 'Build an Underground MegaVault Prison';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-cage-villains-in-power-suppressing-cells' OR Name = 'Cage Villains in Power-Suppressing Cells';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-capture-baby-hope' OR Name = 'Capture Baby Hope';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-change-the-outcome-of-wwii' OR Name = 'Change the Outcome of WWII';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-claim-souls-for-demons' OR Name = 'Claim Souls for Demons';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-clash-of-the-monsters-unleashed' OR Name = 'Clash of the Monsters Unleashed';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-collect-an-interstellar-zoo' OR Name = 'Collect an Interstellar Zoo';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-condition-logan-into-weapon-x' OR Name = 'Condition Logan into Weapon X';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-conquer-paradise-island' OR Name = 'Conquer Paradise Island of Themyscira';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-corrupt-leaders-gotham-city' OR Name = 'Corrupt the Leaders of Gotham City';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-corrupt-the-next-generation-of-heroes' OR Name = 'Corrupt the Next Generation of Heroes';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-corrupt-the-spy-agencies' OR Name = 'Corrupt the Spy Agencies';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-crash-the-moon-into-the-sun' OR Name = 'Crash the Moon into the Sun';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-crown-thor-king-of-asgard' OR Name = 'Crown Thor King of Asgard';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-crush-hydra' OR Name = 'Crush HYDRA';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-crush-them-with-my-bare-hands' OR Name = 'Crush Them With My Bare Hands';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-cursed-pages-of-the-darkhold-tome' OR Name = 'Cursed Pages of the Darkhold Tome';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-cytoplasm-spike-invasion' OR Name = 'Cytoplasm Spike Invasion';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-dark-alliance' OR Name = 'Dark Alliance';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-dark-reign-of-hammer-officers' OR Name = 'Dark Reign of H.A.M.M.E.R. Officers';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-deadlands-hordes-charge-the-wall' OR Name = 'Deadlands Hordes Charge the Wall';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-deadpool-kills-the-marvel-universe' OR Name = 'Deadpool Kills the Marvel Universe';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-deadpool-wants-a-chimichanga' OR Name = 'Deadpool Wants a Chimichanga';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-deadpool-writes-a-scheme' OR Name = 'Deadpool Writes a Scheme';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-demonic-incursion-earth' OR Name = 'Demonic Incursion of the Earth Realm';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-destroy-the-cities-of-earth' OR Name = 'Destroy the Cities of Earth!';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-destroy-the-nova-corps' OR Name = 'Destroy the Nova Corps';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-detonate-the-helicarrier' OR Name = 'Detonate the Helicarrier';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-devolve-with-xerogen-crystals' OR Name = 'Devolve with Xerogen Crystals';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-distract-the-hero' OR Name = 'Distract the Hero';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-divide-and-conquer' OR Name = 'Divide and Conquer';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-drain-mutant-powers-to' OR Name = 'Drain Mutant Powers To...';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-duels-of-science-and-magic' OR Name = 'Duels of Science and Magic';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-earthquake-drains-the-ocean' OR Name = 'Earthquake Drains the Ocean';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-eclipse-light-of-magic' OR Name = 'Eclipse the Light of Magic';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-enshrouded-identity' OR Name = 'Enshrouded Identity';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-enslave-minds-with-the-chitauri-scepter' OR Name = 'Enslave Minds with the Chitauri Scepter';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-enthrone-the-barons-of-battleworld' OR Name = 'Enthrone the Barons of Battleworld';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-epic-super-hero-civil-war' OR Name = 'Epic Super Hero Civil War';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-escape-an-imprisoning-dimension' OR Name = 'Escape an Imprisoning Dimension';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-everybody-hates-deadpool' OR Name = 'Everybody Hates Deadpool';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-explosion-at-the-washington-monument' OR Name = 'Explosion at the Washington Monument';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-fall-of-the-hulks' OR Name = 'Fall of the Hulks';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-fear-itself' OR Name = 'Fear Itself';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-ferry-disaster' OR Name = 'Ferry Disaster';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-find-the-split-personality-killer' OR Name = 'Find the Split Personality Killer';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-five-families-of-crime' OR Name = 'Five Families of Crime';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-flood-the-planet-with-melted-glaciers' OR Name = 'Flood the Planet with Melted Glaciers';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-forge-the-infinity-gauntlet' OR Name = 'Forge the Infinity Gauntlet';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-fragmented-realities' OR Name = 'Fragmented Realities';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-frame-heroes-for-murder' OR Name = 'Frame Heroes for Murder';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-gladiator-pits-of-sakaar' OR Name = 'Gladiator Pits of Sakaar';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-go-after-heroes-loved-ones' OR Name = 'Go After Heroes'' Loved Ones';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-go-back-in-time-to-slay-heroes-ancestors' OR Name = 'Go Back in Time to Slay Heroes'' Ancestors';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-graduation-at-xaviers-x-academy' OR Name = 'Graduation at Xavier''s X-Academy';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-hack-cerebro-servers-to' OR Name = 'Hack Cerebro Servers To...';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-hail-hydra' OR Name = 'Hail Hydra';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-halve-all-life-in-the-universe' OR Name = 'Halve All Life in the Universe';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-hidden-heart-of-darkness' OR Name = 'Hidden Heart of Darkness';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-hire-singularity-investigations-to' OR Name = 'Hire Singularity Investigations To...';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-horror-of-horrors' OR Name = 'Horror of Horrors';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-house-of-m' OR Name = 'House of M';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-hydra-helicarriers-hunt-heroes' OR Name = 'Hydra Helicarriers Hunt Heroes';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-hypnotize-every-human' OR Name = 'Hypnotize Every Human';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-imprison-unregistered-superhumans' OR Name = 'Imprison Unregistered Superhumans';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-inescapable-kyln-space-prison' OR Name = 'Inescapable “Kyln“ Space Prison';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-infiltrate-the-lair-with-spies' OR Name = 'Infiltrate the Lair with Spies';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-intergalactic-kree-nega-bomb' OR Name = 'Intergalactic Kree Nega-Bomb';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-invade-asgard' OR Name = 'Invade Asgard';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-invade-the-daily-bugle-news-hq' OR Name = 'Invade the Daily Bugle News HQ';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-invasion-of-the-venom-symbiotes' OR Name = 'Invasion of the Venom Symbiotes';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-invincible-force-field' OR Name = 'Invincible Force Field';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-kingdom-come' OR Name = 'Kingdom Come';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-lash-city-deadly-tornado' OR Name = 'Lash City with Deadly Tornado';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-last-stand-at-avengers-tower' OR Name = 'Last Stand at Avengers Tower';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-marvel-zombies' OR Name = 'Marvel Zombies';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-mass-produce-war-machine-armor' OR Name = 'Mass Produce War Machine Armor';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-massive-earthquake-generator' OR Name = 'Massive Earthquake Generator';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-master-of-tyrants' OR Name = 'Master of Tyrants';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-master-the-mysteries-of-kung-fu' OR Name = 'Master the Mysteries of Kung-Fu';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-maximum-carnage' OR Name = 'Maximum Carnage';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-merge-earth-bizarro-world' OR Name = 'Merge Earth with Bizarro World';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-midnight-massacre' OR Name = 'Midnight Massacre';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-midtown-bank-robbery' OR Name = 'Midtown Bank Robbery';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-mutant-hunting-super-sentinels' OR Name = 'Mutant-Hunting Super Sentinels';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-mutating-gamma-rays' OR Name = 'Mutating Gamma Rays';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-negative-zone-prison-breakout' OR Name = 'Negative Zone Prison Breakout';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-negative-zone-prison-breakout-base' OR Name = 'Negative Zone Prison Breakout';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-nitro-the-supervillain-threatens-crowds' OR Name = 'Nitro the Supervillain Threatens Crowds';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-nuclear-armageddon' OR Name = 'Nuclear Armageddon';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-organized-crime-wave' OR Name = 'Organized Crime Wave';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-pan-dimensional-plague' OR Name = 'Pan-Dimensional Plague';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-paralyzing-venom' OR Name = 'Paralyzing Venom';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-plunder-wakandas-vibranium' OR Name = 'Plunder Wakanda''s Vibranium';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-poison-lakes-with-nanite-microbots' OR Name = 'Poison Lakes with Nanite Microbots';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-portals-to-the-dark-dimension' OR Name = 'Portals to the Dark Dimension';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-portals-to-the-dark-dimension-base' OR Name = 'Portals to the Dark Dimension';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-predict-future-crime' OR Name = 'Predict Future Crime';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-provoke-a-clash-of-nations' OR Name = 'Provoke a Clash of Nations';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-provoke-the-sovereign-war-fleet' OR Name = 'Provoke the Sovereign War Fleet';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-pull-earth-into-medieval-times' OR Name = 'Pull Earth into Medieval Times';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-pull-reality-into-cyberspace' OR Name = 'Pull Reality Into Cyberspace';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-pull-reality-into-the-negative-zone' OR Name = 'Pull Reality Into the Negative Zone';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-pulse-waves-from-the-negative-zone' OR Name = 'Pulse Waves From the Negative Zone';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-put-humanity-on-trial' OR Name = 'Put Humanity on Trial';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-radioactive-palladium-poisoning' OR Name = 'Radioactive Palladium Poisoning';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-ragnarok-twilight-of-the-gods' OR Name = 'Ragnarok, Twilight of the Gods';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-raid-gene-banks-to' OR Name = 'Raid Gene Banks To...';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-replace-earths-leaders-with-hydra' OR Name = 'Replace Earth''s Leaders with HYDRA';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-replace-earths-leaders-with-killbots' OR Name = 'Replace Earth''s Leaders with Killbots';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-replace-earths-leaders-with-killbots-base' OR Name = 'Replace Earth''s Leaders with Killbots';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-resurrect-heroes-with-norn-stones' OR Name = 'Resurrect Heroes with Norn Stones';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-reveal-heroes-secret-identities' OR Name = 'Reveal Heroes'' Secret Identities';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-ritual-sacrifice-to-summon-chthon' OR Name = 'Ritual Sacrifice to Summon Chthon';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-ruin-the-perfect-wedding' OR Name = 'Ruin the Perfect Wedding';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-shield-vs-hydra-war' OR Name = 'S.H.I.E.L.D. vs. HYDRA War';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-sacrifice-for-the-soul-stone' OR Name = 'Sacrifice for the Soul Stone';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-safeguard-dark-secrets' OR Name = 'Safeguard Dark Secrets';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-save-humanity' OR Name = 'Save Humanity';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-scavenge-alien-weaponry' OR Name = 'Scavenge Alien Weaponry';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-secret-empire-of-betrayal' OR Name = 'Secret Empire of Betrayal';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-secret-hydra-corruption' OR Name = 'Secret HYDRA Corruption';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-secret-invasion-of-the-skrull-shapeshifters' OR Name = 'Secret Invasion of the Skrull Shapeshifters';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-secret-invasion-of-the-skrull-shapeshifters-base' OR Name = 'Secret Invasion of the Skrull Shapeshifters';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-secret-wars' OR Name = 'Secret Wars';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-seize-the-wakandan-throne' OR Name = 'Seize the Wakandan Throne';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-shoot-hulk-into-space' OR Name = 'Shoot Hulk into Space';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-silence-the-witnesses' OR Name = 'Silence the Witnesses';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-sinister-ambitions' OR Name = 'Sinister Ambitions';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-siphon-energy-from-the-quantum-realm' OR Name = 'Siphon Energy from the Quantum Realm';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-sire-vampires-at-the-blood-bank' OR Name = 'Sire Vampires at the Blood Bank';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-smash-two-dimensions-together' OR Name = 'Smash Two Dimensions Together';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-sneak-attack-the-heroes-homes' OR Name = 'Sneak Attack the Heroes'' Homes';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-sniper-rifle-assassins' OR Name = 'Sniper Rifle Assassins';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-splice-humans-with-spider-dna' OR Name = 'Splice Humans with Spider DNA';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-star-lords-awesome-mix-tape' OR Name = 'Star-Lord''s Awesome Mix Tape';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-steal-all-oxygen-on-earth' OR Name = 'Steal All Oxygen on Earth';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-steal-the-weaponized-plutonium' OR Name = 'Steal the Weaponized Plutonium';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-subjugate-earth-with-mega-corporations' OR Name = 'Subjugate Earth with Mega-Corporations';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-subjugate-with-obedience-disks' OR Name = 'Subjugate with Obedience Disks';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-super-hero-civil-war' OR Name = 'Super Hero Civil War';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-superhero-civil-war' OR Name = 'Superhero Civil War';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-superhuman-baseball-game' OR Name = 'Superhuman Baseball Game';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-symbiotic-absorption' OR Name = 'Symbiotic Absorption';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-televised-deathtraps-of-mojoworld' OR Name = 'Televised Deathtraps of Mojoworld';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-terrorize-citizens-joker-venom' OR Name = 'Terrorize Citizens with Joker Venom';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-12-labors-all-star-superman' OR Name = 'The 12 Labors of All-Star Superman';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-clone-saga-the' OR Name = 'The Clone Saga';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-contest-of-champions-the' OR Name = 'The Contest of Champions';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-dark-phoenix-saga-the' OR Name = 'The Dark Phoenix Saga';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-dark-world-of-svartalfheim-the' OR Name = 'The Dark World of Svartalfheim';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-demon-bear-saga-the' OR Name = 'The Demon Bear Saga';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-fountain-of-eternal-life-the' OR Name = 'The Fountain of Eternal Life';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-god-emperor-of-battleworld-the' OR Name = 'The God-Emperor of Battleworld';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-korvac-saga-the' OR Name = 'The Korvac Saga';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-kree-skrull-war-the' OR Name = 'The Kree-Skrull War';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-legacy-virus-the' OR Name = 'The Legacy Virus';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-legacy-virus-the-base' OR Name = 'The Legacy Virus';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-mark-of-khonshu-the' OR Name = 'The Mark of Khonshu';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-the-time-heist' OR Name = 'The Time Heist';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-traitor-the' OR Name = 'The Traitor';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-unbreakable-enigma-code-the' OR Name = 'The Unbreakable Enigma Code';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-tornado-of-terrigen-mists' OR Name = 'Tornado of Terrigen Mists';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-train-black-widows-in-the-red-room' OR Name = 'Train Black Widows in the Red Room';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-transform-citizens-into-demons' OR Name = 'Transform Citizens Into Demons';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-transform-commuters-into-giant-ants' OR Name = 'Transform Commuters into Giant Ants';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-trap-heroes-in-the-microverse' OR Name = 'Trap Heroes in the Microverse';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-trapped-in-the-insane-asylum' OR Name = 'Trapped in the Insane Asylum';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-trash-earth-with-hugest-party-ever' OR Name = 'Trash Earth with Hugest Party Ever';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-turn-the-soul-of-adam-warlock' OR Name = 'Turn the Soul of Adam Warlock';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-unite-the-shards' OR Name = 'Unite the Shards';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-united-states-split-by-civil-war' OR Name = 'United States Split by Civil War';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-unleash-the-abilisk-space-monster' OR Name = 'Unleash the Abilisk Space Monster';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-unleash-the-power-of-the-cosmic-cube' OR Name = 'Unleash the Power of the Cosmic Cube';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-unleash-the-power-of-the-cosmic-cube-base' OR Name = 'Unleash the Power of the Cosmic Cube';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-wager-at-blackjack-for-heroes-souls' OR Name = 'Wager at Blackjack for Heroes'' Souls';
UPDATE Schemes SET Difficulty = 'Hard' WHERE Id = 'scheme-war-for-the-dream-dimension' OR Name = 'War for the Dream Dimension';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-war-of-kings' OR Name = 'War of Kings';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-war-of-the-frost-giants' OR Name = 'War of the Frost Giants';
UPDATE Schemes SET Difficulty = 'Easy' WHERE Id = 'scheme-warp-reality-into-a-tv-show' OR Name = 'Warp Reality into a TV Show';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-weaponize-chemo-against-city' OR Name = 'Weaponize Chemo Against the City';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-weave-a-web-of-lies' OR Name = 'Weave a Web of Lies';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-wipe-heroes-memories' OR Name = 'Wipe Heroes'' Memories';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-world-war-hulk' OR Name = 'World War Hulk';
UPDATE Schemes SET Difficulty = 'Extreme' WHERE Id = 'scheme-x-cutioners-song' OR Name = 'X-Cutioner''s Song';
UPDATE Schemes SET Difficulty = 'Moderate' WHERE Id = 'scheme-x-men-danger-room-goes-berserk' OR Name = 'X-Men Danger Room Goes Berserk';

COMMIT;